name: Continuous Integration Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        #platform: [ ubuntu-latest, macos-latest, windows-latest ]
        #toolchain: [ stable, 1.48.0 ]
        platform: [ ubuntu-latest ]
        toolchain: [ stable ]
        include:
          - toolchain: stable
            check-fmt: true
        #exclude:
        #  - platform: macos-latest
        #    toolchain: 1.48.0
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          profile: minimal
      - name: Build on Rust ${{ matrix.toolchain }}
        run: cargo build --verbose --color always
      - name: Check formatting
        if: matrix.check-fmt
        run: rustup component add rustfmt && cargo fmt --all -- --check
